// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKUw0o-aUNqPmjy28m1Wh14RkaNj7zlJs',
    appId: '1:506614056313:web:922eb31d411d19e210dba8',
    messagingSenderId: '506614056313',
    projectId: 'practiceflutter-80e3a',
    authDomain: 'practiceflutter-80e3a.firebaseapp.com',
    storageBucket: 'practiceflutter-80e3a.firebasestorage.app',
    measurementId: 'G-QV9PP5YQLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi_3DvD0v2OwuclY1sQ87WzEi7cVd68Ls',
    appId: '1:506614056313:android:66b32312feda7e7c10dba8',
    messagingSenderId: '506614056313',
    projectId: 'practiceflutter-80e3a',
    storageBucket: 'practiceflutter-80e3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwjPk6fK9ocG3PNRnc0B6CsxrBkCM9mz8',
    appId: '1:506614056313:ios:1026b321c022e74110dba8',
    messagingSenderId: '506614056313',
    projectId: 'practiceflutter-80e3a',
    storageBucket: 'practiceflutter-80e3a.firebasestorage.app',
    iosBundleId: 'com.example.practiceflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwjPk6fK9ocG3PNRnc0B6CsxrBkCM9mz8',
    appId: '1:506614056313:ios:1026b321c022e74110dba8',
    messagingSenderId: '506614056313',
    projectId: 'practiceflutter-80e3a',
    storageBucket: 'practiceflutter-80e3a.firebasestorage.app',
    iosBundleId: 'com.example.practiceflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKUw0o-aUNqPmjy28m1Wh14RkaNj7zlJs',
    appId: '1:506614056313:web:a0e9b850b3ebd44b10dba8',
    messagingSenderId: '506614056313',
    projectId: 'practiceflutter-80e3a',
    authDomain: 'practiceflutter-80e3a.firebaseapp.com',
    storageBucket: 'practiceflutter-80e3a.firebasestorage.app',
    measurementId: 'G-BVNNMGC5ZW',
  );
}
